### PR TITLE
fix: total alerts displayed per region

### PR DESCRIPTION
**Pull request by yokwejuste**
This PR is linked to the issue #96 

The previous display of the regions list was not caring the correct map of the total alerts display. As for now the current display is as shown below:

image

### CODE REVIEW

**Comment by Asam237** [comment]
@yokwejuste  I have this error at home when I run on your branch. Can you fix this
errer-y

**Comment by yokwejuste** [comment]
> @yokwejuste I have this error at home when I run on your branch. Can you fix this errer-y

Which node version is this alex?

**Comment by yokwejuste** [comment]
Can you try to this again, please?

**Comment by Asam237** [comment]
I have pulled and I still have the same error
yyy

**Comment by yokwejuste** [comment]
@Zaker237 did you check the current branch where you are? I'm just from cloning back my branch and no issue faced.

Seems like you are not on my branch, but an old one. the file indicated there doesn't more exit at that location.

image

**Comment by Zaker237** [comment]
@yokwejuste i'm sur i'm getting you??
still yet i did't work in the frontend

**Comment by yokwejuste** [comment]
Your error is showing a lacking export at the level of a global file at `/fontend/src/pages/add-alert/AddAlert.tsx`. And the current project structure doesn't have that file present. 

May be you should check your branch to be sure to be on the PR branch, seems like you're on an old version.

**Comment by Asam237** [comment]
@yokwejuste I still have the same error, can you fix it?

**Review by Sanix-Darker — CHANGES_REQUESTED** [review]
.

**Review by Asam237 — APPROVED** [review]

**Pull request merged**
