### PR TITLE
Button implementaion

### PR DESCRIPTION
**Pull request by godsakani**
## Fixed
issue #97
## Changes
1. Added button on city villages
2. Fixed spelling on Search button placeholder in list details page

## Difficulties faced
1. Unable to pass parameters to get coordinates
2. Facing issue to implement the functionality

### CODE REVIEW

**Review by Asam237 — CHANGES_REQUESTED** [review]
The best would be when you click on the button it sends you back to the indicated location... 

But for your case, it's like it always sends you to the same point...

https://user-images.githubusercontent.com/34966088/179402868-6cfbeb5e-a34b-46ed-933e-f3231d4c61d9.mp4

**Comment by godsakani** [comment]
> The best would be when you click on the button it sends you back to the indicated location...
> 
> But for your case, it's like it always sends you to the same point...
> 
>  simplescreenrecorder-2022-07-17_15.22.11.mp4

Yes @Asam237  I push the code because I was stock I wanted to show the level I  reached. 
The difficulty is sending to that particular location ?

**Comment by Asam237** [comment]
@godsakani  Try to use the props in the StreepMap component, this is where you will send parameters to your button.

Link to use props => https://fr.reactjs.org/docs/components-and-props.html

**Comment by godsakani** [comment]
> @godsakani Try to use the props in the StreepMap component, this is where you will send parameters to your button.
> 
> Link to use props => https://fr.reactjs.org/docs/components-and-props.html

Hello @Asam237  am just from going through the doc and I have gotton the concept.
Another worry is where am using it in the Streetmap.tsx?

**Comment by Asam237** [comment]
@godsakani  

https://user-images.githubusercontent.com/34966088/180391797-77c62569-cc0a-4fd8-bc7b-b107f1316202.mp4

**Comment by godsakani** [comment]
I close this PR to reopen due to some changes not applying

**Pull request closed without merging**
