### PR TITLE
Function button

### PR DESCRIPTION
**Pull request by godsakani**
## Implement button functionality
# issue #123 

## Changes 
- Added language toggle package
-  Added material library for popups and icons
- Added assets folder to hold languages

## Challenges
- Unable to display button on the screen

### CODE REVIEW

**Comment by Asam237** [comment]
@godsakani

**Comment by Asam237** [comment]
@godsakani you can base yourself on this library

**Comment by Asam237** [comment]
@godsakani  you can base yourself on this library

=> https://react.i18next.com/guides/quick-start

**Comment by godsakani** [comment]
> @godsakani you can base yourself on this library, then resolve conflicts before pushing
> 
> => https://react.i18next.com/guides/quick-start

Ok sir  have being trying to resolve it these days

**Comment by godsakani** [comment]
Branch having conflicts that need to be resolve

**Pull request closed without merging**
