### PR TITLE
Post alert

### PR DESCRIPTION
**Pull request by mouafus**
### User can now post new alert ! 

- Good UI/UX
- Success and error message display

Not working: the posted  alert are not automatically add in global state

### CODE REVIEW

**Comment by Asam237** [comment]
- UI/UX Design, please put the "Report an alert" button on the left, following the alignment of the "List view" button...So as not to hide the map. Like this


Screenshot from 2022-12-09 05-58-50

- The list of districts on the form is not displayed. On that note, here is the end-point to return the list of districts: `http://127.0.0.1:8000/districts`

- Please implement the post method to add an alert.

**Comment by mouafus** [comment]
> * UI/UX Design, please put the "Report an alert" button on the left, following the alignment of the "List view" button...So as not to hide the map. Like this
> 
> 
> Screenshot from 2022-12-09 05-58-50

**Comment by mouafus** [comment]
> * UI/UX Design, please put the "Report an alert" button on the left, following the alignment of the "List view" button...So as not to hide the map. Like this
> 
> 
> Screenshot from 2022-12-09 05-58-50

POV of UX i think it's good like this ! do you really want left alignment ??

@Asam237 @Sanix-Darker @Zaker237

**Comment by Asam237** [comment]
Yes. I do think that the left alignment is the right one. As it was before.

You can also use the following website: https://xn--strungsauskunft-9sb.de/

**Review by Asam237 — APPROVED** [review]

**Pull request merged**
